Fixes cached router view holder's alpha issue
lightning-js/blits pull request #218
Opened 2024-11-15 10:57 UTC by suresh-gangumalla

with default transition, alpha is set to zero for previous route view holder element. if preivous route is configured to keep alive then that view is cached with holder alpha set to zero

Now, if previous route has a custom transition and if it does not contain alpha related prop transition in 'before' or 'in' then holder's alpha will not get updated to 1 from zero set by previous route out transition

2024-11-18 13:38 UTC, jfboeve reviewed
I recommend changing the variable name `isAlphaPropExists` -> `hasAlphaProp`

2024-11-18 20:25 UTC, michielvandergeest commented
> I recommend changing the variable name `isAlphaPropExists` -> `hasAlphaProp`

yes I agree. @suresh-gangumalla can you make the change accordingly?

2024-11-19 07:49 UTC, michielvandergeest requested changes

2024-11-19 07:49 UTC, michielvandergeest commented on src/router/router.js
> +        if (!hasAlphaProp) {
please do a `false` check instead of a `falsey` check here

2024-11-19 07:49 UTC, michielvandergeest commented on src/router/router.js
> +              hasAlphaProp = true
this could be combined in an `else if`?

2024-11-19 16:20 UTC, michielvandergeest approved these changes
LGTM

2024-11-19 16:21 UTC, merged