Added Router BeforeAll Hook
lightning-js/blits pull request #228
Opened 2024-11-27 07:25 UTC by suresh-gangumalla

- Updated Router configuration to include router hooks along with routes from Application instance
- Executing router beforeAll hook on every route navigation

2024-12-10 08:53 UTC, michielvandergeest requested changes
This code looks good, but as far as I understand it's now only possible to provide a router object in the ApplicationConfig

I think ideally we would keep the 'simple' configuration with direct routes (using the `routes`-property, along side the advanced configuration using the `router`-key.

If possible, the Typescript definitions should indicate that only 1 configuration (`routes` vs `router`) is allowed at the same time

2025-03-11 15:36 UTC, michielvandergeest requested changes

2025-03-11 15:36 UTC, michielvandergeest commented on index.d.ts
> +    beforeAll?: (to: Route, from: Route) => string | Route | Promise<string | Route>;
let's name this `beforeEach` instead of `beforeAll`

2025-03-11 15:36 UTC, michielvandergeest commented on index.d.ts
> +     * Router configuration
we should mention that router config take precedence over routes - I guess there's no way to specifiy in typescript that we should either use router or routes but not both? @jfboeve you any idea on this?

2025-03-11 15:36 UTC, michielvandergeest commented on index.d.ts
> +     * @example
mention here as well that router takes precedence

2025-03-11 15:36 UTC, michielvandergeest commented on src/component/setup/index.js
> +  if (config.router || config.routes) setupRouter(component, config.router || config.routes)
we can make an undefined check out of these

2025-03-13 07:49 UTC, jfboeve commented on index.d.ts
> +     * Router configuration
hey sorry for the late response. got a snippet for you [here](https://www.typescriptlang.org/play/?#code/FASwdgLgpgTgZgQwMZQAQGED2BbADpsKSLMOEAc1QG9hgBfW8aeZNAJUwFdmSzKbUqABaZMAawDOALlQByEeImyANMEEwu0aagkQY4cgG0AuvUaRYiFBgJ9qa1Bu6wZszACMAVlCQRZDpy0ZXX0wI1MGYAgAT1w0AEFcXAAbECQECBACXgpUAF4bPAIiCBzKADJUAAoHAUFHTRdUDmcYMtV6hucJAH4ZQgA3WAcGAB9ah3VGmD7UQeHOwKhtEIMTEeAASlokAl1UBCSymUSUtIyssDL8+ynWmTrBBUlXZ6UO+qXtQ3kEZOTMLJTIIGJFgLswPtDrgygAmE5JVLpTLZWy5Ap1L4yH5CP4AlRyCAAd0BER2ewgByOaPIAGYEWdkZdrhiAo1vr9-oDlISSUCPksYA9JsJRC85G8VCKsagcXjSRs6KhgEA)

2025-03-13 10:19 UTC, michielvandergeest commented on src/component/setup/index.js
> +  const routerConfig = config.router !== undefined ? config.router : config.routes !== undefined ? config.routes : undefined
is this part `config.routes !== undefined ? config.routes : undefined` really needed here? 🤔

2025-03-13 16:44 UTC, michielvandergeest approved these changes
LGTM

2025-03-13 16:44 UTC, merged